# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)



platform :ios do
  lane :Spika do
    setup_ci if ENV['CI']
    #increment_build_number(xcodeproj: "Spika.xcodeproj")

    update_code_signing_settings(
		use_automatic_signing: true,
  		path: "Spika.xcodeproj"
	)

    cocoapods(
      clean_install: true,
      podfile: "./CustomPodfile"
    )

    build_app(workspace: "Spika.xcworkspace", 
        silent: true,
	scheme: "Spika", 
	include_bitcode:false,
        export_options:{ 
            manageAppVersionAndBuildNumber: false
        })
    pilot( api_key_path: "fastlane/Q4Y97SL8HA.json",
        skip_waiting_for_build_processing: true)
  end

end
