# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)



platform :ios do
  lane :Spika do
    #increment_build_number(xcodeproj: "Spika.xcodeproj")

    build_app(workspace: "Spika.xcworkspace", 
	scheme: "Spika", 
	include_bitcode:false)
    pilot( api_key_path: "fastlane/Q4Y97SL8HA.json" )
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end

  lane :SpikaDev do
    build_app(workspace: "Spika.xcworkspace", 
       scheme: "Spika Dev", 
       include_bitcode:false)
    pilot( api_key_path: "fastlane/Q4Y97SL8HA.json" )
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end

end
